# Generated by Django 4.2.7 on 2025-09-07 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('cerrada', 'Cerrada')], default='activa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacantes_publicadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vacantes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisando', 'En Revisión'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to=settings.AUTH_USER_MODEL)),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='vacantes.vacante')),
            ],
            options={
                'db_table': 'postulaciones',
                'ordering': ['-fecha_postulacion'],
                'unique_together': {('estudiante', 'vacante')},
            },
        ),
    ]
