# Generated by Django 4.2.7 on 2025-09-07 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacantes', '0001_initial'),
        ('informes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informe',
            name='postulacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informe', to='vacantes.postulacion'),
        ),
    ]
